spring:
  application:
    name: liuguang-api-interface-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 默认 dev 环境
  profiles:
    active: dev
server:
  port: 8405
  servlet:
    context-path: /api/interface-service # 访问前缀