spring:
  application:
    name: liuguang-api-interface-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8405
  servlet:
    context-path: /api/interface-service # 访问前缀

# todo 开源记得脱敏
# todo 看下是否可以重置，先前已经将密钥暴露出去
api:
  resou:
    access-key:
    secret-key:
  weather:
    appid:
    appsecret:


